/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from 'ethers'
import { Provider } from '@ethersproject/providers'

import type { ITransferAndCallReceiver } from '../ITransferAndCallReceiver'

export class ITransferAndCallReceiver__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITransferAndCallReceiver {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ITransferAndCallReceiver
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: 'address',
        name: '_sender',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: '_value',
        type: 'uint256',
      },
      {
        internalType: 'bytes',
        name: '_data',
        type: 'bytes',
      },
    ],
    name: 'onTokenTransfer',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
]
