/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from 'ethers'
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from '@ethersproject/contracts'
import { BytesLike } from '@ethersproject/bytes'
import { Listener, Provider } from '@ethersproject/providers'
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi'

interface SequencerInboxMockInterface extends ethers.utils.Interface {
  functions: {
    'messageCount()': FunctionFragment
  }

  encodeFunctionData(
    functionFragment: 'messageCount',
    values?: undefined
  ): string

  decodeFunctionResult(
    functionFragment: 'messageCount',
    data: BytesLike
  ): Result

  events: {}
}

export class SequencerInboxMock extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  on(event: EventFilter | string, listener: Listener): this
  once(event: EventFilter | string, listener: Listener): this
  addListener(eventName: EventFilter | string, listener: Listener): this
  removeAllListeners(eventName: EventFilter | string): this
  removeListener(eventName: any, listener: Listener): this

  interface: SequencerInboxMockInterface

  functions: {
    messageCount(overrides?: CallOverrides): Promise<[BigNumber]>

    'messageCount()'(overrides?: CallOverrides): Promise<[BigNumber]>
  }

  messageCount(overrides?: CallOverrides): Promise<BigNumber>

  'messageCount()'(overrides?: CallOverrides): Promise<BigNumber>

  callStatic: {
    messageCount(overrides?: CallOverrides): Promise<BigNumber>

    'messageCount()'(overrides?: CallOverrides): Promise<BigNumber>
  }

  filters: {}

  estimateGas: {
    messageCount(overrides?: CallOverrides): Promise<BigNumber>

    'messageCount()'(overrides?: CallOverrides): Promise<BigNumber>
  }

  populateTransaction: {
    messageCount(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'messageCount()'(overrides?: CallOverrides): Promise<PopulatedTransaction>
  }
}
